name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - buildjet-8vcpu-ubuntu-2004
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Latest Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        id: build
        shell: bash
        run: |
          cargo build --all --release

          binary_extension=""

          if [[ "$RUNNER_OS" == "Linux" ]]; then
            binary_path="reward-center-cli-ubuntu-latest"
          fi
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            binary_extension=".exe"
            binary_path="reward-center-cli-windows-latest${binary_extension}"
          fi
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            binary_path="reward-center-cli-macos-intel-latest${binary_extension}"
          fi
          mv "target/release/reward-center-cli${binary_extension}" "${binary_path}"
          echo "::set-output name=binary_path::${binary_path}"
          strip "${binary_path}"

      - name: Release Tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build.outputs.binary_path }}
